---
- name: Make mpv config directory
  file:
    path: "{{ item.home }}/.config/mpv"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: 0700
    state: directory
  with_items: "{{ users }}"

- name: Render the mpv config
  template:
    src: config
    dest: "{{ item.home }}/.config/mpv/config"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: 0700
  with_items: "{{ users }}"
