---
# shigoto
- hosts: localhost
  vars:
    users:
      - name: zwinnerman
        home: /home/zwinnerman
      - name: root
        home: /root
  roles:
    - role: archlinux
      tags: archlinux
    - role: users
      tags: users
    - role: i3
      tags: i3
    - role: slack
      tags: slack
