---
- name: Create users
  user:
    name: "{{ item.name }}"
    home: "{{ item.home }}"
    shell: /bin/zsh
  with_items: "{{ users }}"

- name: Make .config
  file:
    name: "{{ item.home }}/.config"
    state: directory
  with_items: "{{ users }}"

- name: Pull dotfiles
  git:
    repo: https://github.com/hi117/dotFiles.git
    dest: "{{ item.home }}/.config/dotFiles"
    force: yes
  become_user: "{{ item.name }}"
  with_items: "{{ users }}"

- name: Install dotFiles
  file:
    src: "{{ item[0].home }}/.config/dotFiles/{{ item[1] }}"
    dest: "{{ item[0].home }}/{{ item[1] }}"
    state: link
  with_nested:
    - "{{ users }}"
    - - .vimrc
      - .vim
      - .zshrc
      - .tmux.conf
      - .gdbinit
      - .radare2rc
      - .Xresources
      - .config/kitty
      - .config/nvim
      - .config/libinput-gestures.conf

- name: Install dircolors
  file:
    src: "{{ item.home }}/.config/dotFiles/dircolors-solarized/dircolors.256dark"
    dest: "{{ item.home }}/.dircolors"
    state: link

- name: Make .ssh
  file:
    dest: "{{ item.home }}/.ssh"
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: 0700
  with_items: "{{ users }}"

- name: Render authorized_keys
  template:
    src: authorized_keys.j2
    dest: "{{ item.home }}/.ssh/authorized_keys"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: 0400
  with_items: "{{ users }}"
